# add the linters you want stickler to use for this project
linters:
  stylelint:
    # indicate where is the config file for stylelint
    config: "stylelint.config.js"
files:
  ignore:
    - "styles/scss/main-styles.scss"
    - "styles/scss/_base.scss"
    - "styles/scss/_color-config.scss"
    - "styles/scss/_typo-config.scss"
    - "styles/scss/_layouts.scss"
    - "styles/scss/_widgets.scss"
    #For ignoring a file/folder
# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config
# find full documentation here: https://stickler-ci.com/docs